=== axel-klinger/grapheneditor/Beispiele/Vorlagen/Verkehrsnetz.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    
    <xsd:element name="Verkehrsnetz" type="VerkehrsnetzTyp"/>
    
    <xsd:complexType name="VerkehrsnetzTyp">
        <xsd:sequence>
            <xsd:element name="Verkehrsknoten" type="VerkehrsknotenTyp"/>
            <xsd:element name="Straßenabschnitte" type="StraßenabschnittTyp"/>
        </xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="VerkehrsknotenTyp">
        <xsd:sequence>
            <xsd:element name="Knoten" type="KnotenTyp" minOccurs="1" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="StraßenabschnittTyp">
        <xsd:sequence>
            <xsd:element name="Abschnitt" type="AbschnittTyp" minOccurs="1" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="KnotenTyp">
        <xsd:sequence>
            <xsd:element name="x" type="xsd:integer"/>
            <xsd:element name="y" type="xsd:integer"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:integer"/>
    </xsd:complexType>
    
    <xsd:complexType name="AbschnittTyp">
        <xsd:sequence>
            <xsd:element name="von" type="xsd:integer"/>
            <xsd:element name="nach" type="xsd:integer"/>
        </xsd:sequence>
    </xsd:complexType>
</xsd:schema>

=== axel-klinger/grapheneditor/Beispiele/Vorlagen/old/Verkehrsnetz-Nordstadt.xml
<?xml version="1.0" encoding="UTF-8"?>
<Verkehrsnetz xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/D:/Axel/Promotion/Sprache/Verkehrsnetz.xsd">
    <Verkehrsknoten>
        <Knoten id="001">
            <x>100</x>
            <y>100</y>
        </Knoten>
        <Knoten id="002">
            <x>200</x>
            <y>200</y>
        </Knoten>
    </Verkehrsknoten>
    <Straßenabschnitte>
        <Abschnitt>
            <von>001</von>
            <nach>002</nach>
        </Abschnitt>
    </Straßenabschnitte>
</Verkehrsnetz>
